---
language: ruby
rvm:
  - 2.3
services:
  - docker

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq
  - sudo apt-get install -qq ruby ruby-dev build-essential autoconf
  - gem install bundler
  - ruby --version

install:
  - bundle install

script:
    - ./test/run-tests.sh
after_success:
    - echo "Success"
